
version: 2.1

commands:

  print_pipeline_id:
    description: "printing the pipleline id "
    parameters:
      var:
        type: string
        default: "not enetered "


    steps:

    - run: echo <<parameters.var>>  




jobs:
  say-hello:
   
    docker:
      - image: cimg/base:stable
   
    steps:
 
      - run:  echo Hello, World! > ~/output.txt
    
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print-outputfile :
   
    docker:
      - image: cimg/base:stable
   
    steps:
     
      - run:  cat output.txt
    
      - attach_workspace:
         at: ~/


  print-var:

    docker:
      - image: cimg/base:stable   

    steps:

    - print_pipeline_id:
        var: $CIRCLE_WORKFLOW_ID


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print-outputfile :
          requires: 
             - say-hello
      - print-var





